# Generated by Django 2.0.6 on 2018-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20180701_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agd_hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agd_hora_inicio',
            field=models.TimeField(),
        ),
    ]
