# Generated by Django 2.0.6 on 2018-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20180701_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agd_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agd_hora_fim',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agd_hora_inicio',
            field=models.CharField(max_length=255),
        ),
    ]
